import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const cliOnly = process.argv[2] === 'cli';

// The headless CLI: the same metrics and rendering, Node instead of Obsidian. A
// separate entry point rather than a flag on the plugin bundle because the two
// have opposite externals — the plugin leaves `obsidian` unresolved for the app
// to supply at runtime, and a Node build must not reference it at all.
if (cliOnly) {
	await esbuild.build({
		banner: { js: '#!/usr/bin/env node\n' + banner },
		entryPoints: ['src/cli.ts'],
		bundle: true,
		platform: 'node',
		format: 'esm',
		target: 'node18',
		external: [...builtinModules, ...builtinModules.map((m) => `node:${m}`)],
		logLevel: 'info',
		treeShaking: true,
		outfile: 'bin/oura-metrics.mjs',
	});
	process.exit(0);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
